---
title: "mixed_models"
output: pdf_document
---

```{r}
library(lmerTest) 
library(tidyverse)
library(modelsummary)
```

## No time element 
```{r}
df <- read.csv("/Users/amitsasson/PycharmProjects/DSSGx/Prakhar_drafts/data_from_2010_to_2019_unemployment_rate.csv")
head(df)
df$ags2 <- factor(df$ags2)
df$ags5 <- factor(df$ags5)
df$cluster <- factor(df$cluster)


```

#### without clutster/kreis
```{r}
fit1 <- lmer(mean_unemployment_rate ~ median_income + total_area + X2019_population + (1 | ags2), df)
summary(fit1)
get_gof(fit1)
```

#### with clutster
```{r}
fit2 <- lmer(mean_unemployment_rate ~ cluster + median_income  + total_area + X2019_population + (1 | ags2), df)
summary(fit2)
coef(fit2)
get_gof(fit2)
```


## Time data 

#### creating the dataset needed 
```{r}
df2 <- read.csv("/Users/amitsasson/PycharmProjects/DSSGx/final_dfs/for_modeling/df_final_date_wide_2007.csv")
df <- df2 %>% select(ags5, unemployment_rate, date, number_of_start_ups)
df <- df %>% select(-data_index)
labor <- read.csv("/Users/amitsasson/PycharmProjects/DSSGx/final_dfs/labor_market_by_date.csv")
tmp <- read.csv("/Users/amitsasson/PycharmProjects/DSSGx/corona_data_sets/arbeitsmarktentwicklung.csv") %>% select(bundesland, ags5)

df <- df %>% mutate(the_date = as.Date(date))
tmp <- tmp %>% select(ags5, bundesland)
df <- df %>% left_join(tmp, by = "ags5")
df$bundesland <- factor(df$bundesland)

ggplot(df, aes(x = the_date, y = number_of_start_ups, group = ags5, color = bundesland)) + 
  geom_line() + 
    labs(x = "Date", y = "Unemployment rate", color = "Bundesland", title = "Unemployment rate by date for each Kreis") + 
  geom_vline(xintercept =as.numeric(as.Date("2009-12-01")), linetype="dashed", 
                color = "black", size=0.8) + 
   geom_vline(xintercept =as.numeric(as.Date("2019-12-01")), linetype="dashed", 
                color = "black", size=0.8) 


ggplot(df, aes(x = the_date, y = unemployment_rate, group = ags5, color = bundesland)) + 
  geom_line() + 
    labs(x = "Date", y = "Unemployment rate", color = "Bundesland", title = "Unemployment rate by date for each Kreis") + 
  geom_vline(xintercept =as.numeric(as.Date("2009-12-01")), linetype="dashed", 
                color = "black", size=0.8) + 
   geom_vline(xintercept =as.numeric(as.Date("2019-12-01")), linetype="dashed", 
                color = "black", size=0.8) 


df %>% group_by(the_date, bundesland) %>% summarise(unemployment_rate=mean(unemployment_rate)) %>% 
ggplot(aes(x = the_date, y = unemployment_rate, group = bundesland, color = bundesland)) + 
  geom_line() + 
    labs(x = "Date", y = "Unemployment rate", color = "Bundesland", title = "Unemployment rate by date for each Bundesland") + 
  geom_vline(xintercept =as.numeric(as.Date("2009-12-01")), linetype="dashed", 
                color = "black", size=0.8) + 
   geom_vline(xintercept =as.numeric(as.Date("2019-12-01")), linetype="dashed", 
                color = "black", size=0.8) 


df <- df %>% 
  left_join(labor, by = c("ags5" = "ags5", "ags2" = "ags2")) %>% 
  left_join(tmp, by = c("ags5" = "ags5"))
df$ags2 <- factor(df$ags2)
df$ags5 <- factor(df$ags5)
df$bundesland <- factor(df$bundesland)
df$cluster <- factor(df$cluster , levels=c(1,2,0), labels= c("Biggest two cities", "Middle-Big size cities", "Small cities and rural areas"))

df <- df %>% 
        rename(the_date = date) %>% 
        mutate(the_date = as.Date(as.character(the_date)))

head(df)
```

#### plot 
```{r}
ggplot(df, aes(x = the_date, y = unemployment_rate)) + 
  geom_point() 



df %>% 
  group_by(cluster, the_date) %>% 
  summarise(mean_unemployment_rate = sum(unemployment_rate %*% X2019_population)/sum(X2019_population)) %>% 
ggplot(aes(x = the_date, y = mean_unemployment_rate, color = cluster)) + 
  geom_point()  + 
  geom_line()  +  
  labs(x = "Date", y = "Unemployment rate", color = "Bundesland", title = "Unemployment rate by date for each cluster") +
  scale_y_continuous(limits = c(2, 12), breaks = seq(2, 12, by = 2)) 

df %>% 
  group_by(bundesland, the_date) %>% 
  summarise(mean_unemployment_rate = sum(unemployment_rate %*% X2019_population)/sum(X2019_population)) %>% 
ggplot(aes(x = the_date, y = mean_unemployment_rate, color = bundesland)) + 
  geom_point()  + 
  geom_line() +  
  labs(x = "Date", y = "Unemployment rate", color = "Bundesland", title = "Unemployment rate by date for each bundesland") +
  scale_y_continuous(limits = c(0, 18), breaks = seq(0, 18, by = 2)) -> p 

df %>% 
ggplot(aes(x = the_date, y = unemployment_rate, color = bundesland, group = ags5)) + 
  geom_point()  + 
  geom_line() + 
  labs(x = "Date", y = "Unemployment rate", color = "Bundesland", title = "Unemployment rate by date for each kreis")  +
  scale_y_continuous(limits = c(0, 18), breaks = seq(0, 18, by = 2)) -> q 

 q+p+plot_layout(guides = 'collect')
```
#### LMM 
```{r}
fit4 <- lmer(unemployment_rate ~ date + cluster + median_income + X2019_population + (1 | ags2) + (1 | ags5), df)
summary(fit4)

get_gof(fit4)
fit5 <- lmer(unemployment_rate ~ . + (1 | ags2) + (1 | ags5), df)

# step(fit5, keep.effs = "Assessor")
```

#### TIme series 
```{r}
where_i_am <- function(location)
{
  if(car == "right") {return("uk")}
  return("south africa")
}
```



